site_name: pytkdocs
site_description: Load Python objects documentation.
site_url: https://pytkdocs.github.io/
repo_url: https://github.com/pawamoy/pytkdocs
repo_name: pawamoy/pytkdocs

nav:
  - Overview: "index.md"
  - Reference:
    - cli.py: "reference/cli.md"
  - Contributing: "contributing.md"
  - Code of Conduct: "code_of_conduct.md"
  - Changelog: "changelog.md"
  - Credits: "credits.md"

theme:
  name: "material"

extra_css:
  - css/mkdocstrings.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      watch:
        - src/pytkdocs
